language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
deploy:
  skip_cleanup: true
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project todoapp-tuhin --token $FIREBASE_TOKEN
