language: node_js
node_js:
  - "11.0"
before_install:
  - npm i -g npm@version-number
script:
 - npm install
 - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project todoapp-tuhin --token $FIREBASE_TOKEN
