language: node_js
node_js:
  - "stable"
script:
 - echo "Deploy!!"
 - npm run build
deploy:
  skip_cleanup: true
  project: ./build/
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project todoapp-tuhin --token $FIREBASE_TOKEN
